### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by dereklieu** [cumulus-nasa/pvl#1]
mileswwatkins [6:40 PM]  
Here's the loose spec it's covering, and not all of it's implemented

[6:40]  
https://pds.nasa.gov/documents/sr/Chapter12.pdf

[6:40]  
Here's the precise spec it's covering https://pirlwww.lpl.arizona.edu/software/PPVL/CCSDS-641.0-B-2.pdf

[6:45]  
@derek: Here's what I'd suggest doing:

1. _Don't_ read the whole spec documents; at worst, read a couple paragraphs here or there if you need a sanity check. You might not need to read anything.
2. _Don't_ take more than an hour or so, at worst.
3. Find ~3 PVL documents, either from the spec documents, from NASA's sample PDRs or PANs for us (http://e4ftl01.cr.usgs.gov:40520/TEST_B/Cumulus/PDR/), or elsewhere. Run them through the parsing function, then run that object through the serializing function. See if the output looks similar to the original PVL document.
4. Do a loose overview of the code, and let me know if anything looks out of place.

**Comment by mileswwatkins** [comment]
@dereklieu, I don't think I ever saw feedback on this. No rush at all, though, but would be nice to have your second set of eyes.

**Comment by dereklieu** [comment]
Nope didn't get to it, but thanks for reminding me!
